### ISSUE TITLE
login and register are not working,needs update

### ISSUE THREAD

**Issue by sayinmehmet47** [DawnMD/next-auth-credentials#3]
login is not redirect to mainpage

**Comment by DawnMD** [comment]
For login, you'll be redirected to the change password page. It's an intended action

For signup, there is no redirect as it depends on server response which is out of the scope for next-auth tutorial

**Comment by sayinmehmet47** [comment]
also after register success, and persons mail added to database, cannot login by account that registered

**Comment by DawnMD** [comment]
Tested this and can confirm login works with the same account that's been registered with!

**Comment by DawnMD** [comment]
Closing this issue
